gmail_credential_jsonpath: "/secure-read-only-to-me-path/credentials.json"

gmail_auth_picklepath: "/secure-read-only-to-me-path/gmail.pickle"

log_debug: "on"

scopes:
  - "https://www.googleapis.com/auth/gmail.readonly"

data_basepath: "data"
